version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cryptography
    versions:
    - ">= 3.0.a, < 3.1"
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.4.2
    - 1.4.3
    - 1.4.5
    - 1.4.7
    - 1.4.9
  - dependency-name: humanize
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: cryptography
    versions:
    - 3.3.1
