"""Team Members

Revision ID: a7cad8facf57
Revises: 2a13ff670ebf
Create Date: 2018-07-11 09:38:04.790449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cad8facf57'
down_revision = '2a13ff670ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_team_creator_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.create_index(op.f('ix_team_creator_id'), 'team', ['creator_id'], unique=False)
    op.create_table('team_member',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invite_email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('invite_secret', sa.String(length=255), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], name=op.f('fk_team_member_inviter_id_user')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_member_team_id_team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_team_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_member'))
    )
    op.create_index(op.f('ix_team_member_team_id'), 'team_member', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_team_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_team_creator_id'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
