"""empty message

Revision ID: ec9963c4438e
Revises: a7cad8facf57
Create Date: 2018-07-31 23:12:00.728087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9963c4438e'
down_revision = 'a7cad8facf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_plan',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_plan_id', sa.String(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('trial_seconds', sa.Integer(), nullable=True),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_plan'))
    )
    op.create_table('stripe_subscription',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('product_plan_id', sa.Integer(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_plan_id'], ['product_plan.id'], name=op.f('fk_stripe_subscription_product_plan_id_product_plan')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_stripe_subscription_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_subscription'))
    )
    op.create_index(op.f('ix_stripe_subscription_team_id'), 'stripe_subscription', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_subscription_team_id'), table_name='stripe_subscription')
    op.drop_table('stripe_subscription')
    op.drop_table('product_plan')
    # ### end Alembic commands ###
