# Constants
REQUIRE_EMAIL_CONFIRMATION = True

EMAIL_CONFIRMATION_SALT = 'email-confirmation-key'
PASSWORD_RESET_SALT = 'pass-reset-key'
PURCHASE_LICENSE_SALT = 'license-purchase-key'

PASSWORD_RESET_VALIDITY_SECONDS = 86400
